name: ldap_tool
description: Web-based LDAP tool for Active Directory management.
version: 1.0.0

environment:
  sdk: ^3.12.2

dependencies:
  path: ^1.9.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_static: ^1.1.0
  dartdap: ^0.11.0
  dotenv: ^4.2.0
  mailer: ^6.1.0
  win32: ^5.0.0
  ffi: ^2.1.0
